import createClient from "openapi-fetch";
import type {paths} from "./generated/api"; // generated by openapi-typescript

export const fetchClient = createClient<paths>({baseUrl: "https://api/v1/",});


fetchClient.use({
    onRequest: ({request, params}) => {
        console.log(`Request: ${request.method} ${request.url}`);
    },
    onResponse: ({response}) => {
        console.log(`Response: ${response.status} ${response.url}`);
    },
    onError: ({error}) => {
        console.error(`Error: ${error}`);
    },
})

const getAdvisories = async (assignmentId: number, page: number) => {
    return await fetchClient.GET("/assignments/{assignment_id}/accepted_assignments", {
        params: {
            path: {
                assignment_id: assignmentId
            },
            query: {
                page: 1,
                per_page: 10
            }
        }
    });
};


