import createClient from "openapi-react-query";
import type { paths } from "./my-openapi-3-schema";
import {fetchClient} from "./fetch"; // generated by openapi-typescript

const $api = createClient(fetchClient);
