# docker/Dockerfile.seed
FROM node:18-alpine

WORKDIR /app

# bcrypt와 pg를 설치
RUN npm init -y && npm install bcrypt pg

# 애플리케이션 파일 복사
COPY postgres/placeholder-data.js /app/placeholder-data.js
COPY postgres/seed-data.js /app/seed-data.js

# 시드 스크립트 실행
CMD ["node", "seed-data.js"]